/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.Cadastro;

import java.awt.Component;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import javax.swing.JTextField;

/**
 *
 * @author thiag
 */
public class TeladeReserva extends javax.swing.JFrame {

    /**
     * Creates new form abaQuartos
     */
    public TeladeReserva() {
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        panelMainReserv = new javax.swing.JPanel();
        lblMaintxtCadReserv = new javax.swing.JLabel();
        lblNumerodoQuarto = new javax.swing.JLabel();
        lblIDdosquartos = new javax.swing.JLabel();
        lblIDcliente = new javax.swing.JLabel();
        lblValorTotalReserv = new javax.swing.JLabel();
        btnVoltarReserv = new javax.swing.JButton();
        btnConfirmarReservaReserv = new javax.swing.JButton();
        btnLimparReserv = new javax.swing.JButton();
        txtCampoValorQuart = new javax.swing.JTextField();
        ComboNumerodoQuarto = new javax.swing.JComboBox<>();
        lblCheckin = new javax.swing.JLabel();
        lbCheckout = new javax.swing.JLabel();
        campoFtxtIDdoquarto = new javax.swing.JFormattedTextField();
        campoFtxtIDcliente = new javax.swing.JFormattedTextField();
        campoFtxtIDCheckIn = new javax.swing.JFormattedTextField();
        campoFtxtIDCheckOut = new javax.swing.JFormattedTextField();
        btnRealizarcheckincheckout = new javax.swing.JButton();
        lblMaintxt2ListReserv = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblReservas = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reservas");

        panelMainReserv.setBackground(new java.awt.Color(128, 129, 186));

        lblMaintxtCadReserv.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaintxtCadReserv.setText("Cadastro de Reservas:");

        lblNumerodoQuarto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNumerodoQuarto.setText("Número do Quarto:");

        lblIDdosquartos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblIDdosquartos.setText("ID do Quarto:");

        lblIDcliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblIDcliente.setText("ID do cliente:");

        lblValorTotalReserv.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblValorTotalReserv.setText("Valor total:");

        btnVoltarReserv.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnVoltarReserv.setText("Voltar");
        btnVoltarReserv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarReservActionPerformed(evt);
            }
        });

        btnConfirmarReservaReserv.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnConfirmarReservaReserv.setText("Confirmar reserva");
        btnConfirmarReservaReserv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarReservaReservActionPerformed(evt);
            }
        });

        btnLimparReserv.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnLimparReserv.setText("Limpar");

        txtCampoValorQuart.setText("1500,00");
        txtCampoValorQuart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCampoValorQuartActionPerformed(evt);
            }
        });

        ComboNumerodoQuarto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "301" }));

        lblCheckin.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblCheckin.setText("Data Check-in:");

        lbCheckout.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbCheckout.setText("Data Check-out:");

        campoFtxtIDdoquarto.setText("null");
        campoFtxtIDdoquarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoFtxtIDdoquartoActionPerformed(evt);
            }
        });

        campoFtxtIDcliente.setText("null");
        campoFtxtIDcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoFtxtIDclienteActionPerformed(evt);
            }
        });

        campoFtxtIDCheckIn.setText("null");

        campoFtxtIDCheckOut.setText("null");
        campoFtxtIDCheckOut.setToolTipText("");

        btnRealizarcheckincheckout.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnRealizarcheckincheckout.setText("Realizar Check-in/Check-out");

        javax.swing.GroupLayout panelMainReservLayout = new javax.swing.GroupLayout(panelMainReserv);
        panelMainReserv.setLayout(panelMainReservLayout);
        panelMainReservLayout.setHorizontalGroup(
            panelMainReservLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainReservLayout.createSequentialGroup()
                .addGroup(panelMainReservLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainReservLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblMaintxtCadReserv, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMainReservLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelMainReservLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMainReservLayout.createSequentialGroup()
                                .addComponent(lblNumerodoQuarto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboNumerodoQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelMainReservLayout.createSequentialGroup()
                                .addComponent(lblIDdosquartos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelMainReservLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoFtxtIDcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoFtxtIDdoquarto, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoFtxtIDCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panelMainReservLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelMainReservLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblCheckin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblIDcliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelMainReservLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelMainReservLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbCheckout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblValorTotalReserv, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelMainReservLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCampoValorQuart, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoFtxtIDCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelMainReservLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(panelMainReservLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConfirmarReservaReserv)
                            .addComponent(btnRealizarcheckincheckout)
                            .addComponent(btnVoltarReserv)
                            .addComponent(btnLimparReserv))))
                .addGap(380, 380, Short.MAX_VALUE))
        );
        panelMainReservLayout.setVerticalGroup(
            panelMainReservLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainReservLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblMaintxtCadReserv)
                .addGap(23, 23, 23)
                .addGroup(panelMainReservLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumerodoQuarto)
                    .addComponent(ComboNumerodoQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelMainReservLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDdosquartos)
                    .addComponent(campoFtxtIDdoquarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(panelMainReservLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDcliente)
                    .addComponent(campoFtxtIDcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelMainReservLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCheckin)
                    .addComponent(campoFtxtIDCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelMainReservLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCheckout)
                    .addComponent(campoFtxtIDCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(panelMainReservLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorTotalReserv)
                    .addComponent(txtCampoValorQuart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRealizarcheckincheckout)
                .addGap(18, 18, 18)
                .addComponent(btnConfirmarReservaReserv)
                .addGap(18, 18, 18)
                .addComponent(btnVoltarReserv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLimparReserv)
                .addGap(38, 38, 38))
        );

        jDesktopPane1.setLayer(panelMainReserv, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMainReserv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMainReserv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblMaintxt2ListReserv.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaintxt2ListReserv.setText("Lista de reservas:");

        tblReservas.setBackground(new java.awt.Color(153, 153, 153));
        tblReservas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        tblReservas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblReservas.setForeground(new java.awt.Color(51, 102, 255));
        tblReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "Pedro", null, null, "301"},
                {"", null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Check-in", "Check-out", "Quarto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblReservas.setToolTipText("Reservas registradas");
        tblReservas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tblReservas.setColumnSelectionAllowed(true);
        tblReservas.setGridColor(new java.awt.Color(44, 74, 110));
        tblReservas.setShowGrid(true);
        jScrollPane2.setViewportView(tblReservas);
        tblReservas.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMaintxt2ListReserv, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 388, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblMaintxt2ListReserv)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarReservActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarReservActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoltarReservActionPerformed

    private void btnConfirmarReservaReservActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarReservaReservActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmarReservaReservActionPerformed

    private void txtCampoValorQuartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCampoValorQuartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCampoValorQuartActionPerformed

    private void campoFtxtIDdoquartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoFtxtIDdoquartoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoFtxtIDdoquartoActionPerformed

    private void campoFtxtIDclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoFtxtIDclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoFtxtIDclienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeladeReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeladeReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeladeReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeladeReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeladeReserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboNumerodoQuarto;
    private javax.swing.JButton btnConfirmarReservaReserv;
    private javax.swing.JButton btnLimparReserv;
    private javax.swing.JButton btnRealizarcheckincheckout;
    private javax.swing.JButton btnVoltarReserv;
    private javax.swing.JFormattedTextField campoFtxtIDCheckIn;
    private javax.swing.JFormattedTextField campoFtxtIDCheckOut;
    private javax.swing.JFormattedTextField campoFtxtIDcliente;
    private javax.swing.JFormattedTextField campoFtxtIDdoquarto;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbCheckout;
    private javax.swing.JLabel lblCheckin;
    private javax.swing.JLabel lblIDcliente;
    private javax.swing.JLabel lblIDdosquartos;
    private javax.swing.JLabel lblMaintxt2ListReserv;
    private javax.swing.JLabel lblMaintxtCadReserv;
    private javax.swing.JLabel lblNumerodoQuarto;
    private javax.swing.JLabel lblValorTotalReserv;
    private javax.swing.JPanel panelMainReserv;
    private javax.swing.JTable tblReservas;
    private javax.swing.JTextField txtCampoValorQuart;
    // End of variables declaration//GEN-END:variables
}
