/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.Cadastro;

/**
 *
 * @author thiag
 */
public class TelaLogindeFuncionário extends javax.swing.JFrame {

    /**
     * Creates new form Telafuncionario
     */
    public TelaLogindeFuncionário() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMaintxt1CadFunc = new javax.swing.JLabel();
        pnlCadFunc = new javax.swing.JPanel();
        lblNomeFunc = new javax.swing.JLabel();
        lblCargoFunc = new javax.swing.JLabel();
        lblLoginFunc = new javax.swing.JLabel();
        lblSenhaFunc = new javax.swing.JLabel();
        CampoFtxtNomeFunc = new javax.swing.JFormattedTextField();
        CampoFtxtCargoFunc = new javax.swing.JFormattedTextField();
        CampoFtxtLoginFunc = new javax.swing.JFormattedTextField();
        BtnCadastrarFunc = new javax.swing.JButton();
        BtnLimparFunc = new javax.swing.JButton();
        BtnVoltarFunc = new javax.swing.JButton();
        campoSenhaFunc = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaRegistroFunc = new javax.swing.JTable();
        lblMaintext2ListFunc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LogindeFuncionários");

        jPanel1.setBackground(new java.awt.Color(128, 129, 186));

        lblMaintxt1CadFunc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMaintxt1CadFunc.setText(" Login de Funcionários:");

        pnlCadFunc.setBackground(new java.awt.Color(239, 242, 255));
        pnlCadFunc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 255), new java.awt.Color(51, 0, 153), null, new java.awt.Color(0, 0, 0)));

        lblNomeFunc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblNomeFunc.setText("Nome:");

        lblCargoFunc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCargoFunc.setText("Cargo:");

        lblLoginFunc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblLoginFunc.setText("Login:");

        lblSenhaFunc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblSenhaFunc.setText("Senha:");

        CampoFtxtNomeFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoFtxtNomeFuncActionPerformed(evt);
            }
        });

        BtnCadastrarFunc.setText("Cadastrar");

        BtnLimparFunc.setText("Limpar");

        BtnVoltarFunc.setText("Voltar");
        BtnVoltarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVoltarFuncActionPerformed(evt);
            }
        });

        campoSenhaFunc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        campoSenhaFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSenhaFuncActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCadFuncLayout = new javax.swing.GroupLayout(pnlCadFunc);
        pnlCadFunc.setLayout(pnlCadFuncLayout);
        pnlCadFuncLayout.setHorizontalGroup(
            pnlCadFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadFuncLayout.createSequentialGroup()
                .addGroup(pnlCadFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCadFuncLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlCadFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlCadFuncLayout.createSequentialGroup()
                                .addGroup(pnlCadFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblCargoFunc, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                    .addComponent(lblNomeFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlCadFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CampoFtxtNomeFunc, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                                    .addComponent(CampoFtxtCargoFunc)))
                            .addGroup(pnlCadFuncLayout.createSequentialGroup()
                                .addComponent(lblSenhaFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoSenhaFunc))
                            .addGroup(pnlCadFuncLayout.createSequentialGroup()
                                .addComponent(lblLoginFunc)
                                .addGap(18, 18, 18)
                                .addComponent(CampoFtxtLoginFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlCadFuncLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(BtnCadastrarFunc)
                        .addGap(146, 146, 146)
                        .addComponent(BtnLimparFunc)
                        .addGap(18, 18, 18)
                        .addComponent(BtnVoltarFunc)))
                .addContainerGap(322, Short.MAX_VALUE))
        );
        pnlCadFuncLayout.setVerticalGroup(
            pnlCadFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadFuncLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCadFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeFunc)
                    .addComponent(CampoFtxtNomeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCadFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCargoFunc)
                    .addComponent(CampoFtxtCargoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCadFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoginFunc)
                    .addComponent(CampoFtxtLoginFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCadFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenhaFunc)
                    .addComponent(campoSenhaFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlCadFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCadastrarFunc)
                    .addComponent(BtnLimparFunc)
                    .addComponent(BtnVoltarFunc))
                .addGap(16, 16, 16))
        );

        jSeparator1.setBackground(new java.awt.Color(128, 129, 186));
        jSeparator1.setForeground(new java.awt.Color(128, 129, 186));

        tblListaRegistroFunc.setAutoCreateRowSorter(true);
        tblListaRegistroFunc.setBackground(new java.awt.Color(153, 153, 153));
        tblListaRegistroFunc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        tblListaRegistroFunc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblListaRegistroFunc.setForeground(new java.awt.Color(51, 102, 255));
        tblListaRegistroFunc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(128821), "Josué", null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "null", "null"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblListaRegistroFunc.setAlignmentX(1.0F);
        tblListaRegistroFunc.setGridColor(new java.awt.Color(44, 74, 110));
        tblListaRegistroFunc.setShowGrid(true);
        jScrollPane1.setViewportView(tblListaRegistroFunc);

        lblMaintext2ListFunc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMaintext2ListFunc.setText("Lista de Funcionários:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblMaintxt1CadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pnlCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 58, Short.MAX_VALUE)
                        .addComponent(lblMaintext2ListFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaintxt1CadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaintext2ListFunc))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(pnlCadFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(227, 227, 227)))))
                .addGap(69, 69, 69))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoFtxtNomeFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoFtxtNomeFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoFtxtNomeFuncActionPerformed

    private void BtnVoltarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoltarFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnVoltarFuncActionPerformed

    private void campoSenhaFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSenhaFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSenhaFuncActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogindeFuncionário.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogindeFuncionário.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogindeFuncionário.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogindeFuncionário.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogindeFuncionário().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCadastrarFunc;
    private javax.swing.JButton BtnLimparFunc;
    private javax.swing.JButton BtnVoltarFunc;
    private javax.swing.JFormattedTextField CampoFtxtCargoFunc;
    private javax.swing.JFormattedTextField CampoFtxtLoginFunc;
    private javax.swing.JFormattedTextField CampoFtxtNomeFunc;
    private javax.swing.JPasswordField campoSenhaFunc;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCargoFunc;
    private javax.swing.JLabel lblLoginFunc;
    private javax.swing.JLabel lblMaintext2ListFunc;
    private javax.swing.JLabel lblMaintxt1CadFunc;
    private javax.swing.JLabel lblNomeFunc;
    private javax.swing.JLabel lblSenhaFunc;
    private javax.swing.JPanel pnlCadFunc;
    private javax.swing.JTable tblListaRegistroFunc;
    // End of variables declaration//GEN-END:variables
}
